### ISSUE TITLE
Port to ESP32

### ISSUE THREAD

**Issue by merlin2533** [ESPWortuhr/Multilayout-ESP-Wordclock#328]
For more Power on HTML side?
More flexible to it?

**Comment by dbambus** [comment]
Hello @merlin2533, 

so far it has not been requested and I would like to continue supporting the ESP8266. I think it is possible to port the code within a few hours, but I don't have a timeline when. It should be a solution where most of the code is the same to have some kind of base and only change the platform. 

Cheers David

**Comment by merlin2533** [comment]
We have the problem that is so slow loading the webpage that it need 25minutes somtetimes it crashes

Von: David Panusch ***@***.***>
Gesendet: Montag, 13. November 2023 20:31
An: ESPWortuhr/Multilayout-ESP-Wordclock ***@***.***>
Cc: Markus Straub ***@***.***>; Mention ***@***.***>
Betreff: Re: [ESPWortuhr/Multilayout-ESP-Wordclock] Port to ESP32 (Issue #328)


Hello @merlin2533<https://github.com/merlin2533>,

so far it has not been requested and I would like to continue supporting the ESP8266. I think it is possible to port the code within a few hours, but I don't have a timeline when. It should be a solution where most of the code is the same to have some kind of base and only change the platform.

Cheers David

**Comment by dbambus** [comment]
I noticed yesterday as well. I'll have a look into that. Ist wasn't so some months ago. Maybe something changed in the WifiManager Lib.

**Comment by merlin2533** [comment]
In my Point of View IT Looks in language topic. That was deson of more Power with esp32

Gesendet von Outlook für Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by merlin2533** [comment]
Loading of Page need 25min, do you have an idea to solve it?

**Comment by dbambus** [comment]
Can you test an older release directly from the Binary provided, a Version like V3.0, if the problem still occurs ? 

I guess it is a problem with the WiFi manager build we are using right now.

**Comment by merlin2533** [comment]
2.8 ist working but older not

Gesendet von Outlook für Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by dbambus** [comment]
Okay,

i will investigate further, but this is an interesting hint. 

Thanks @merlin2533

**Comment by merlin2533** [comment]
When you need help, let me know
Otherwise or a testobject i have a cnc here with plasma and wood


Von: David Panusch ***@***.***>
Gesendet: Montag, 20. November 2023 10:01
An: ESPWortuhr/Multilayout-ESP-Wordclock ***@***.***>
Cc: Markus Straub ***@***.***>; Mention ***@***.***>
Betreff: Re: [ESPWortuhr/Multilayout-ESP-Wordclock] Port to ESP32 (Issue #328)


Okay,

i will investigate further, but this is an interesting hint.

Thanks @merlin2533<https://github.com/merlin2533>

**Comment by dbambus** [comment]
Hello @merlin2533,

Could you test the current version in the main branch? I have made some changes, including using a specific build ( 2.0.16-rc2) of the WiFiManager library. I have a strong suspicion that recent changes in it are causing the connection to timeout. That's why I fall back to the latest stable version. 
In my test setup, everything has worked so far. 

Cheers 
David

**Comment by merlin2533** [comment]
Have you found a potion to port it? or why it happen?

**Comment by nikolai2111** [comment]
Hello everyone,

What is the current status?

I would be very interested in porting to the ESP32 boards. Since I am currently planning to create a board that should also have a certain cross-compatibility and should be available for hobbyists easily and for a long time (e.g. order online, assembled or just as a board). The data sheet of the ESP8266 recommends using a ‘newer’ chip, the ‘long-term commitment’ from Espressif states the EOL for the ESP8622 as sometime in 2029, the replacement board, which is specified in the data sheet as a replacement, is not specified, so the EOL is unknown. Therefore, I would rather focus on the newer boards. As far as I understand it, porting would also mean that many more different ESPs (C, S & H series) could be used, as the code would be easily interchangeable between the new ESP32s (adaptation of platformio.ini).

I have already tried this myself. However, I failed due to a lack of knowledge and experience with the ESPs, as certain functions would have to be rewritten in some cases. 

However, before I can design this circuit board, I would like to create a breadboard prototype. Is it possible to discuss the priority of the issue? Especially if you say it can be done in a few hours, I would be very interested. I could also help you with the hardware tests as I bought some ESP DevKits for this project (ESP32-C3 / C6 & S3).

What do you think?

**Comment by dbambus** [comment]
Hey, 

in short, I tried yesterday some adjustments for ESP32 and I was able to build it :-) here is a Version, which should work, as a alpha. Can you test it at first ? 

LED Pin is preconfigured to PIN 2

[V3.3_Dev_ESP32.zip](https://github.com/user-attachments/files/17001614/V3.3_Dev_ESP32.zip)

I will make the branch available anytime soon. 

Mit freundlichen Grüßen
David

**Comment by merlin2533** [comment]
I will do a test in the next days

Gesendet von Outlook für Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by nikolai2111** [comment]
Thank you very much for your quick response!

I tried it today, unfortunately without success. I failed to flash it (I have never done it with the .bin files).
I would welcome a branch to upload everything via PIO. That way I can also test the code on several new ESP32s (C3, C6 & S3).

**Comment by dbambus** [comment]
Done with the latest Release https://github.com/ESPWortuhr/Multilayout-ESP-Wordclock/releases/tag/V4.0.0

**Comment by nikolai2111** [comment]
@dbambus, great job! I'm currently playing around with the new release, very nice Job!
I also have seen that you are using LaTeX for the documentation, another very nice step forward!

I'm currently designing a PCB and which I want to contribute to this repo as a pull request, but this can take a littebit of time.

As I have seen from the code and to mention it for the community I figured out that the periphery is connected to the following pins (of the ESP32):
- A0: LDR
- D21 & D22: I2C for the BH1750 (maybe also the RTC?)
- D27: for the LED stripes
